name: allure-report

on:
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!main'

jobs:
  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Retrieve previous Allure history
      - name: Get Allure History
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run Tests
        run: npm run wdio

      # Step 5: Generate Allure report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: gh-pages
          keep_reports: 20

      # Step 6: Deploy the report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages


